Modificaciones de estado de las tarjetas: 
INSERT INTO auditoria_tarjeta VALUES (9, 2, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (10, 113, 'Activa', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (11, 36, 'Activa', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (12, 2, 'Activa', 'Bloqueada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (13, 67, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (14, 32, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (15, 11, 'Bloqueada', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (16, 113, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (17, 23, 'Bloqueada', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (18, 36, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (19, 87, 'Bloqueada', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (20, 23, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (21, 178, 'Bloqueada', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (22, 90, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (23, 122, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (24, 113, 'Activa', 'Bloqueada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (25, 74, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (26, 134, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (27, 113, 'Bloqueada', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (28, 21, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (29, 183, 'Bloqueada', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (30, 156, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (31, 11, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (32, 122, 'Bloqueada', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (30, 156, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (31, 11, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (32, 122, 'Bloqueada', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (33, 87, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (34, 32, 'Activa', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (35, 12, 'Bloqueada', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (36, 54, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (37, 122, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (38, 21, 'Activa', 'Bloqueada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (39, 90, 'Activa', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (40, 67, 'Activa', 'Bloqueada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (41, 36, 'Activa', 'Bloqueada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (42, 133, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (43, 3, 'Bloqueada', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (44, 3, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (45, 44, 'Bloqueada', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (46, 65, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (47, 43, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (48, 87, 'Activa', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (49, 56, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (50, 34, 'Cancelada', 'Activa', DEFAULT);

-- Inserciones corregidas (51-100)
INSERT INTO auditoria_tarjeta VALUES (51, 23, 'Activa', 'Bloqueada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (52, 12, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (53, 32, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (54, 122, 'Activa', 'Bloqueada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (55, 112, 'Activa', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (56, 113, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (57, 89, 'Activa', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (58, 77, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (59, 66, 'Activa', 'Bloqueada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (60, 56, 'Activa', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (61, 43, 'Activa', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (62, 32, 'Activa', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (63, 67, 'Bloqueada', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (64, 90, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (65, 56, 'Cancelada', 'Bloqueada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (66, 4, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (67, 3, 'Activa', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (68, 1, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (69, 57, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (70, 98, 'Activa', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (71, 76, 'Activa', 'Bloqueada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (72, 54, 'Activa', 'Bloqueada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (73, 34, 'Activa', 'Bloqueada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (74, 32, 'Cancelada', 'Bloqueada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (75, 45, 'Activa', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (76, 67, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (77, 88, 'Bloqueada', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (78, 82, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (79, 34, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (80, 43, 'Cancelada', 'Bloqueada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (81, 45, 'Cancelada', 'Bloqueada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (82, 5, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (83, 34, 'Activa', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (84, 67, 'Activa', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (85, 88, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (86, 65, 'Activa', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (87, 54, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (88, 33, 'Bloqueada', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (89, 22, 'Bloqueada', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (90, 65, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (91, 34, 'Cancelada', 'Bloqueada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (92, 32, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (93, 76, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (94, 56, 'Bloqueada', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (95, 54, 'Activa', 'Bloqueada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (96, 55, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (97, 23, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (98, 143, 'Activa', 'Bloqueada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (99, 122, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (100, 123, 'Bloqueada', 'Activa', DEFAULT);

-- Inserciones corregidas (101-128)
INSERT INTO auditoria_tarjeta VALUES (101, 167, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (102, 25, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (103, 126, 'Bloqueada', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (104, 176, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (105, 148, 'Bloqueada', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (106, 23, 'Activa', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (107, 52, 'Activa', 'Bloqueada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (108, 145, 'Cancelada', 'Bloqueada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (109, 153, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (110, 12, 'Activa', 'Bloqueada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (111, 145, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (112, 164, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (113, 164, 'Activa', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (114, 165, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (115, 143, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (116, 124, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (117, 164, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (118, 56, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (119, 23, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (120, 54, 'Bloqueada', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (121, 76, 'Activa', 'Bloqueada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (122, 34, 'Bloqueada', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (123, 23, 'Activa', 'Bloqueada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (124, 12, 'Bloqueada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (125, 65, 'Activa', 'Bloqueada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (126, 122, 'Activa', 'Cancelada', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (127, 178, 'Cancelada', 'Activa', DEFAULT);
INSERT INTO auditoria_tarjeta VALUES (128, 156, 'Activa', 'Bloqueada', DEFAULT);
UPDATE tarjetas SET estado = 'Activa', fecha_actualizacion = CURRENT_DATE WHERE tarjeta_id IN (2);
UPDATE tarjetas SET estado = 'Cancelada', fecha_actualizacion = CURRENT_DATE WHERE tarjeta_id IN (113, 36);
UPDATE tarjetas SET estado = 'Bloqueada', fecha_actualizacion = CURRENT_DATE WHERE tarjeta_id IN (2);
UPDATE tarjetas SET estado = 'Activa', fecha_actualizacion = CURRENT_DATE WHERE tarjeta_id IN (67, 32, 113);
UPDATE tarjetas SET estado = 'Cancelada', fecha_actualizacion = CURRENT_DATE WHERE tarjeta_id IN (11);
UPDATE tarjetas SET estado = 'Activa', fecha_actualizacion = CURRENT_DATE WHERE tarjeta_id IN (36);
UPDATE tarjetas SET estado = 'Cancelada', fecha_actualizacion = CURRENT_DATE WHERE tarjeta_id IN (23, 87);
UPDATE tarjetas SET estado = 'Activa', fecha_actualizacion = CURRENT_DATE WHERE tarjeta_id IN (23);
UPDATE tarjetas SET estado = 'Cancelada', fecha_actualizacion = CURRENT_DATE WHERE tarjeta_id IN (178);
UPDATE tarjetas SET estado = 'Activa', fecha_actualizacion = CURRENT_DATE WHERE tarjeta_id IN (90, 122, 74, 134);
UPDATE tarjetas SET estado = 'Bloqueada', fecha_actualizacion = CURRENT_DATE WHERE tarjeta_id IN (113);
UPDATE tarjetas SET estado = 'Activa', fecha_actualizacion = CURRENT_DATE WHERE tarjeta_id IN (21);
UPDATE tarjetas SET estado = 'Cancelada', fecha_actualizacion = CURRENT_DATE WHERE tarjeta_id IN (113, 183);
UPDATE tarjetas SET estado = 'Activa', fecha_actualizacion = CURRENT_DATE WHERE tarjeta_id IN (156, 11);
UPDATE tarjetas SET estado = 'Cancelada', fecha_actualizacion = CURRENT_DATE WHERE tarjeta_id IN (122);
-- Grupo 1: Actualizaciones a 'Activa'
UPDATE tarjetas SET estado = 'Activa', fecha_actualizacion = CURRENT_DATE WHERE tarjeta_id IN (156, 87, 54, 122, 133, 3, 65, 43, 56, 34, 23, 32, 113, 77, 4, 1, 57, 67, 82, 5, 88, 54, 33, 22, 65, 32, 76, 55, 23, 122, 123, 167, 25, 176, 153, 145, 164, 165, 143, 124, 164, 56, 23, 23, 178);

-- Grupo 2: Actualizaciones a 'Bloqueada'
UPDATE tarjetas SET estado = 'Bloqueada', fecha_actualizacion = CURRENT_DATE WHERE tarjeta_id IN (21, 67, 36, 23, 122, 66, 56, 76, 54, 34, 32, 43, 45, 34, 54, 143, 52, 145, 12, 76, 23, 65, 156);

-- Grupo 3: Actualizaciones a 'Cancelada'
UPDATE tarjetas SET estado = 'Cancelada', fecha_actualizacion = CURRENT_DATE WHERE tarjeta_id IN (122, 32, 12, 90, 3, 113, 45, 87, 89, 56, 43, 32, 67, 112, 98, 45, 34, 67, 88, 65, 126, 148, 23, 164, 54, 34, 122);
